# Generated by Django 3.0.3 on 2020-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('contact_form', 'Contact form')], help_text='The label field of application (topic).', max_length=50)),
                ('item', models.CharField(choices=[('first_name', 'First name'), ('last_name', 'Last name'), ('email', 'email'), ('where_from', 'Where from'), ('age', 'Age'), ('object', 'Object'), ('message', 'Message'), ('news_agreement', 'Agreement to receive the newsletters'), ('privacy_agreement', 'Agreement to the privacy policy'), ('submit', 'Submit button'), ('clear', 'Clear form')], help_text='The item the label will apply to.', max_length=100)),
                ('label', models.CharField(help_text='The label which will be visible.', max_length=150)),
                ('label_it', models.CharField(help_text='The label which will be visible.', max_length=150, null=True)),
                ('label_en', models.CharField(help_text='The label which will be visible.', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Message text content.', max_length=250)),
                ('topic', models.CharField(blank=True, choices=[('contact_form', 'Contact form')], help_text='The message field of application (topic).', max_length=50, null=True)),
                ('text_to_users', models.CharField(blank=True, help_text='Message text exposed to users.', max_length=250, null=True)),
                ('text_to_users_it', models.CharField(blank=True, help_text='Message text exposed to users.', max_length=250, null=True)),
                ('text_to_users_en', models.CharField(blank=True, help_text='Message text exposed to users.', max_length=250, null=True)),
            ],
        ),
    ]
